import React from 'react'
import './Popup.css'

const content = [
  {
    name: 'photo0',
    title: "Royce Hall aftermath",
    image: 'https://wp.dailybruin.com/images/2024/05/NG3.jpg',
    description: "Pieces of the barricade lie near the entrance of Royce Hall’s archway, covered in signage and graffiti. A section of the graffiti in white reads “ACAB,” an acronym for “All cops are bastards,” while another in green reads “Fuck Fascism.” On two sides of a pillar, graffiti in green says, “In the darkness and the dawn, a red star rises” – a reference to the concluding lines of a Langston Hughes poem about Bolshevik leader Vladimir Lenin.",
    byline: '(Nicolas Greamo/Daily Bruin senior staff)',
    date: '5/2',
    fulldate: 'May 2, 2024 6:15 a.m.',
    },
    {
    name: 'photo1',
    title: "Powell Library aftermath",
    image: 'https://wp.dailybruin.com/images/2024/05/NG4.jpg',
    description: "A large Palestinian flag lies on the ground in front of Powell Library. Around 5 a.m. May 2, a law enforcement officer removed the flag from its mount toward the center of the encampment and threw it in the direction of Royce Hall. The flag rests beside the scattered remains of the encampment, sprawling out between the two hallmark buildings of UCLA’s campus.",
    byline: '(Nicolas Greamo/Daily Bruin senior staff)',
    date: '5/2',
    fulldate: 'May 2, 2024 6:17 a.m.',
    },
    {
    name: 'photo2',
    title: "Defusing tensions",
    image: 'https://wp.dailybruin.com/images/2024/05/3.attack.ZI_.1.jpg',
    description: "An individual walks between members of the encampment and counter-protest groups in an attempt to defuse the tension and stave off fighting.",
    byline: '(Zoraiz Irshad/Daily Bruin senior staff)',
    date: '5/1',
    fulldate: 'May 1, 2024 1:04 a.m.',
    },
    {
    name: 'photo3',
    title: "Encampment press conference",
    image: 'https://wp.dailybruin.com/images/2024/05/7.sweep_.BJM_1.jpg',
    description: "With the towers of Royce Hall in the background, protesters held Palestinian flags and signs up. The protesters appeared at the top of Janss Steps during a press conference held by the encampment at 3 p.m. May 1.",
    byline: '(Brandon Morquecho/Daily Bruin senior staff)',
    date: '5/1',
    fulldate: 'May 1, 2024 6:46 p.m.',
    },
    {
    name: 'photo4',
    title: "California Highway Patrol removes encampment barriers",
    image: 'https://wp.dailybruin.com/images/2024/05/15.sweep_.ZI_5.jpg',
    description: "A division of California Highway Patrol used tools to cut through the ropes and zip ties holding together the metal barricades around the encampment, preparing for the ensuing sweep.",
    byline: '(Zoraiz Irshad/Daily Bruin senior staff)',
    date: '5/2',
    fulldate: 'May 2, 2024 3:08 a.m.',
    },
    {
    name: 'photo5',
    title: "Early Stages of Encampment",
    image: 'https://wp.dailybruin.com/images/2024/04/1.NG2_.jpg',
    description: "A view from above the encampment April 26 shows two sprawling groups of tents separated by a walkway and surrounded by wooden barricades and metal fencing.",
    byline: '(Nicolas Greamo/Daily Bruin senior staff)',
    date: '4/26',
    fulldate: 'April 26, 2024 6:16 p.m.',
    },
    {
    name: 'photo6',
    title: "Law enforcement and protester standoff",
    image: 'https://wp.dailybruin.com/images/2024/05/web.news_.studentsdenounce.BJM_.jpg',
    description: "Police officers wearing riot gear between Royce Hall and Rolfe Hall stood facing a large group of protesters. Law enforcement cleared the Palestine solidarity encampment at UCLA in the early hours of May 2 after a dispersal order was issued.",
    byline: '(Brandon Morquecho/Daily Bruin senior staff)',
    date: '5/1',
    fulldate: 'May 1, 2024 9:13 p.m.',
    },
    {
    name: 'photo7',
    title: "Counter-protester climbs fence",
    image: 'https://wp.dailybruin.com/images/2024/04/web.news_.encampment.midnight.4.28.24JCC.jpg',
    description: "A counter-protester attempts to breach a fence outside the encampment in Dickson Plaza in the early hours of April 28. The fence was placed the night of April 25 by security in front of the encampment – which was organized by Students for Justice in Palestine and the UC Divest Coalition at UCLA.",
    byline: '(Joseph Crosby/Daily Bruin senior staff)',
    date: '4/27',
    fulldate: 'April 27, 2024 11:09 p.m.',
    },
    {
    name: 'photo8',
    title: "Encampment cleanup",
    image: 'https://wp.dailybruin.com/images/2024/05/web.news_.encampmentcleanup.JC_.jpg',
    description: "UCLA staff cleared Dickson Plaza of debris using excavators and other heavy machinery following the May 2 police sweep of the Palestine solidarity encampment.",
    byline: '(Jeremy Chen/Daily Bruin senior staff)',
    date: '5/2',
    fulldate: 'May 2, 2024 11:14 a.m.',
    },
    {
    name: 'photo9',
    title: "Pro-Palestine protester chanting",
    image: 'https://wp.dailybruin.com/images/2024/05/12.sweep_.MF_4.jpg',
    description: "A pro-Palestine protester chanted at the top of Janss Steps after a group of police officers initially retreated from the encampment.",
    byline: '(Myka Fromm/Daily Bruin senior staff)',
    date: '5/2',
    fulldate: 'May 2, 2024 nan',
    },
    {
    name: 'photo10',
    title: "Los Angeles County Sheriff’s Department buses transport detained protesters",
    image: 'https://wp.dailybruin.com/images/2024/05/NG11.jpg',
    description: "Law enforcement officers from the Los Angeles County Sheriff’s Department and California Highway Patrol gathered near a bus being used to transport detained protesters after the sweep of the encampment the morning of May 2.",
    byline: '(Nicolas Greamo/Daily Bruin senior staff)',
    date: '5/2',
    fulldate: 'May 2, 2024 6:41 a.m.',
    },
    {
    name: 'photo11',
    title: "California Highway Patrol officers blocking pathway",
    image: 'https://wp.dailybruin.com/images/2024/05/14.sweep_.BJM_5.jpg',
    description: "A man wearing a jacket that reads “Anti Genocide Social Club” recorded a livestream of a line of California Highway Patrol officers between Royce Hall and Haines Hall. The line of officers ordered a clearing of the area and threatened to arrest three Daily Bruin reporters.",
    byline: '(Brandon Morquecho/Daily Bruin senior staff)',
    date: '5/2',
    fulldate: 'May 2, 2024 nan',
    },
    {
    name: 'photo12',
    title: "Jum'ah prayer",
    image: 'https://wp.dailybruin.com/images/2024/04/4.AGS2_.jpg',
    description: "Some protesters in the Dickson Plaza encampment participated in Jum'ah prayer while other members of the protest formed a circle around those praying.",
    byline: '(Aidan Sun/Assistant Photo editor)',
    date: '4/26',
    fulldate: 'April 26, 2024 12:23 p.m.',
    },
    {
    name: 'photo13',
    title: "Palestine solidarity encampment banner",
    image: 'https://wp.dailybruin.com/images/2024/04/8.DS4_-1.jpg',
    description: "A banner that reads “Palestine Solidarity Encampment” featured a watermelon and stood across from a food and necessities tent. The watermelon has become an unofficial symbol of protest for Palestine supporters, representing defiance and resistance against the occupation of Palestine.",
    byline: '(Darlene Sanzon/Assistant Photo editor)',
    date: '4/25',
    fulldate: 'April 25, 2024 9:29 a.m.',
    },
    {
    name: 'photo14',
    title: "Encampment posters",
    image: 'https://wp.dailybruin.com/images/2024/04/9.AGS1_.jpg',
    description: "Protesters placed homemade signs with pro-Palestine slogans around a second layer of metal fencing, which was erected by UCLA officials the morning of April 26 after they constructed an initial layer the night of April 25.",
    byline: '(Aidan Sun/Assistant Photo editor)',
    date: '4/26',
    fulldate: 'April 26, 2024 12:02 p.m.',
    },
    {
    name: 'photo15',
    title: "Dickson Plaza solidarity circle",
    image: 'https://wp.dailybruin.com/images/2024/04/12.JZH3_.jpg',
    description: "Protesters encircled Dickson Plaza with arms intertwined in a display of solidarity.",
    byline: '(Julia Zhou/Daily Bruin senior staff)',
    date: '4/25',
    fulldate: 'April 25, 2024 5:32 p.m.',
    },
    {
    name: 'photo16',
    title: "Counter-protesters gather at Royce Hall",
    image: 'https://wp.dailybruin.com/images/2024/04/17.JZH1_.jpg',
    description: "Counter-protesters gathered in front of Royce Hall the afternoon of April 25. The counter-protesters and protesters, separated by Contemporary Services Corporation security officers, confronted each other at Dickson Plaza.",
    byline: '(Julia Zhou/Daily Bruin senior staff)',
    date: '4/25',
    fulldate: 'April 25, 2024 5:47 p.m.',
    },
    {
    name: 'photo17',
    title: "Pro-Israel rally stage",
    image: 'https://wp.dailybruin.com/images/2024/04/3-ZI2.jpg',
    description: "Following a musical performance at the pro-Israel rally – which was organized in response to the encampment – a singer shared an embrace with another event speaker.",
    byline: '(Zoraiz Irshad/Daily Bruin senior staff)',
    date: '4/28',
    fulldate: 'April 28, 2024 2:47 p.m.',
    },
    {
    name: 'photo18',
    title: "Pro-Israel protester rips poster",
    image: 'https://wp.dailybruin.com/images/2024/04/10-SS1.jpg',
    description: "A crowd watched a counter-protester use a switchblade to rip through a poster displaying support for Palestine during a rally led by the Israeli American Council on April 28.",
    byline: '(Sharla Steinman/Daily Bruin senior staff)',
    date: '4/28',
    fulldate: 'April 28, 2024 11:58 a.m.',
    },
    {
    name: 'photo19',
    title: "Demonstrators waving Palestinian flag",
    image: 'https://wp.dailybruin.com/images/2024/04/13-JC2.jpg',
    description: "Pro-Palestine demonstrators wave a large Palestinian flag on Portola Plaza after a pro-Israel rally Sunday, April 28.",
    byline: '(Jeremy Chen/Daily Bruin senior staff)',
    date: '4/28',
    fulldate: 'April 28, 2024 12:17 p.m.',
    },
    {
    name: 'photo20',
    title: "Setting up the encampment",
    image: 'DSC_6861',
    description: "Following the spread of student-organized encampments across the country, UCLA students in support of Palestine established a Palestine solidarity encampment the morning of April 25. The encampment, which lasted just over a wees, was filled with tents and surrounded by wooden and metal barricades.",
    byline: '(Darlene Sanzon/Assistant Photo editor)',
    date: '4/25',
    fulldate: 'April 25, 2024 8:45 a.m.',
    },
    {
    name: 'photo21',
    title: "Faculty and staff solidarity",
    image: 'DSC_6950',
    description: "UCLA faculty and staff members joined the encampment alongside students, while others offered solidarity. UCLA academic workers from United Auto Workers Local 4811 went on strike May 28 after the union filedd unfair labor practice charges against the UC.",
    byline: '(Darlene Sanzon/Assistant Photo editor)',
    date: '4/25',
    fulldate: 'April 25, 2024 8:58 a.m.',
    },
    {
    name: 'photo22',
    title: "Barrier decorations",
    image: 'DSC_3119',
    description: "Pro-Palestine demonstrators set up the encampment in Dickson Plaza between Royce Hall and Powell Library. The eastern wall of the encampment was decorated with posters and a banner with \"UCLA Law says Free Palestine\" printed on it.",
    byline: '(Mia Tavares/Daily Bruin senior staff)',
    date: '4/25',
    fulldate: 'April 25, 2024 8:39 a.m.',
    },
    {
    name: 'photo23',
    title: "Palestinian flags on Powell Library",
    image: 'DSC_3125',
    description: "Hours after the encampment was first established, the scaffolding surrounding Powell Library's front entrance was decorated with Palestinian flags, posters and graffiti. On Thursday morning, UCLA administration restricted access to Powell Library and Royce Hall to those with BruinCards.",
    byline: '(Mia Tavares/Daily Bruin senior staff)',
    date: '4/25',
    fulldate: 'April 25, 2024 8:41 a.m.',
    },
    {
    name: 'photo24',
    title: "Encampment growing",
    image: 'DSC_3123',
    description: "Students for Justice in Palestine at UCLA called upon UCLA students to join the encampment on Instagram. The organization urged the UC to divest from companies \"complicit in the Israeli occupation, apartheid, and genocide\" of Palestinians, disclose the UC's and UCLA Foundation's assets, sever ties with LAPD, call for an immediate and permanent ceasefire in the Gaza Strip, and boycott Israeli academic institutions.",
    byline: '(Mia Tavares/Daily Bruin senior staff)',
    date: '4/25',
    fulldate: 'April 25, 2024 8:40 a.m.',
    },
    {
    name: 'photo25',
    title: "Instructional boards",
    image: 'DSC_3164',
    description: "Demonstrators put up several large wooden boards around the encampment that detailed Palestine's history. Inside the encampment, organizers invited guests to hold teach-ins providing information related to the Palestinian cause.",
    byline: '(Mia Tavares/Daily Bruin senior staff)',
    date: '4/25',
    fulldate: 'April 25, 2024 8:55 a.m.',
    },
    {
    name: 'photo26',
    title: "Large presence at encampment",
    image: 'DSC02373',
    description: "At its peak on the first day of the encampment, nearly 300 attendees were present. Around 100 people slept in Dickson Plaza overnight inside tents or on the lawn.",
    byline: '(Anna Dai-Liu/Daily Bruin senior staff)',
    date: '4/25',
    fulldate: 'April 25, 2024 1:18 p.m.',
    },
    {
    name: 'photo27',
    title: "Physical confrontations by counter-protesters",
    image: 'DSC_7316',
    description: "Counter-protesters demonstrating against the pro-Palestine encampment spent the first day waving Israeli flags and shouting insults at members of the encampment. At least one counter-protester entered the encampment and confronted its members. Over the course of the day, a few counter-protesters instigated physical confrontations with pro-Palestine demonstrators.",
    byline: '(Julia Zhou/Daily Bruin senior staff)',
    date: '4/25',
    fulldate: 'April 25, 2024 4:37 p.m.',
    },
    {
    name: 'photo28',
    title: "Injured protester receives medical treatment",
    image: 'DBJ_6629',
    description: "Following physical confrontations between counter-protesters and members of the encampment during the first evening, a pro-Palestine protester received medical treatment for an ankle injury and was carried away from Dickson Plaza around 9 p.m.",
    byline: '(Zimo Li/Photo Editor)',
    date: '4/25',
    fulldate: 'April 25, 2024 7:54 p.m.',
    },
    {
    name: 'photo29',
    title: "Establishing emergency exits",
    image: 'DBJ_6748',
    description: "UCLA Fire Marshal Ricardo Barboza entered the encampment to discuss establishing emergency exits with organizers.",
    byline: '(Zimo Li/Photo Editor)',
    date: '4/25',
    fulldate: 'April 25, 2024 8:11 p.m.',
    },
    {
    name: 'photo30',
    title: "Putting Up posters",
    image: 'DSC_8539',
    description: "Pro-Palestine protesters continued putting up posters outside the encampment on the second day. The encampment had an area dedicated to designing posters and banners that had a collection of art supplies.",
    byline: '(Aidan Sun/Assistant Photo editor)',
    date: '4/26',
    fulldate: 'April 26, 2024 11:59 a.m.',
    },
    {
    name: 'photo31',
    title: "Morning of day 2",
    image: 'DSC_8726',
    description: "In response to the previous day's confrontations, UCLA officials set up two layers of metal barricades around the encampment. Overnight, some counter-protesters attempted to prevent those inside the encampment from sleeping by using a speaker to play loud music and shouting.",
    byline: '(Darlene Sanzon/Assistant Photo editor)',
    date: '4/26',
    fulldate: 'April 26, 2024 3:11 p.m.',
    },
    {
    name: 'photo32',
    title: "Passing the time",
    image: 'DSC_8759',
    description: "Protesters inside the encampment played games and made posters to pass the time. The encampment organizers provided meals to attendees with the help of donations. ",
    byline: '(Darlene Sanzon/Assistant Photo editor)',
    date: '4/26',
    fulldate: 'April 26, 2024 3:15 p.m.',
    },
    {
    name: 'photo33',
    title: "Music in the encampment",
    image: 'DSC_8774',
    description: "Demonstrators frequently played music inside the encampment. Many protesters wore keffiyehs, traditional Arab headscarfs popularized by Palestinian political figures such as Yasser Arafat, in solidarity with the Palestinian cause.",
    byline: '(Darlene Sanzon/Assistant Photo editor)',
    date: '4/26',
    fulldate: 'April 26, 2024 3:18 p.m.',
    },
    {
    name: 'photo34',
    title: "Encampment chants",
    image: 'DSC_8880',
    description: "Pro-Palestine protesters spent much of their time repeating chants such as, \"Free, free Palestine.\" At times, these chants were met with competing ones from pro-Israel protesters, including \"Free the hostages.\"",
    byline: '(Darlene Sanzon/Assistant Photo editor)',
    date: '4/26',
    fulldate: 'April 26, 2024 3:58 p.m.',
    },
    {
    name: 'photo35',
    title: "CSC security separating protesters",
    image: 'DSC_8909',
    description: "Pro-Israel counter-protesters continued to amass outside the encampment on the second day. CSC security officers hired by UCLA stood between the encampment and counter-protesters, using their bicycles to separate the two groups. ",
    byline: '(Darlene Sanzon/Assistant Photo editor)',
    date: '4/26',
    fulldate: 'April 26, 2024 4:14 p.m.',
    },
    {
    name: 'photo36',
    title: "Night of day 2",
    image: '0DB_8268',
    description: "On the second night, hundreds of students slept in Dickson Plaza, accessing the surrounding buildings to use the restroom. The encampment had access to a generator, which allowed students to charge their devices without having to leave.",
    byline: '(Jessica Allen/Daily Bruin)',
    date: '4/26',
    fulldate: 'April 26, 2024 10:32 p.m.',
    },
    {
    name: 'photo37',
    title: "Top view of encampment",
    image: 'DSC_3346',
    description: "An above view of the encampment from Royce Hall shows the large number of tents that occupied the area, displaying the size of the encampment relative to Dickson Plaza.",
    byline: '(Leydi Cris Cobo Cordon/Daily Bruin senior staff)',
    date: '4/26',
    fulldate: 'April 26, 2024 3:14 p.m.',
    },
    {
    name: 'photo38',
    title: "Fortifying barriers",
    image: '0DB_8203',
    description: "Members of the encampment fortified the barriers using power tools and wooden pallets. ",
    byline: '(Nicolas Greamo/Daily Bruin senior staff)',
    date: '4/26',
    fulldate: 'April 26, 2024 8:44 p.m.',
    },
    {
    name: 'photo39',
    title: "Growing in numbers",
    image: '0DB_8301',
    description: "The encampment continued to grow in numbers on day three as people waited in line to enter the encampment.   ",
    byline: '(Dylan Du/Daily Bruin senior staff)',
    date: '4/27',
    fulldate: 'April 27, 2024 1:03 p.m.',
    },
    {
    name: 'photo40',
    title: "Counter-protesters by Royce Hall",
    image: 'DSC_4866',
    description: "Counter-protesters arrived around 11 p.m. with megaphones and large speakers and gathered on the front steps of Royce Hall. They spelled out \"Bring them home\" using candles, referring to the Israeli hostages held by Palestinian political party and militant group Hamas since Oct. 7. The group of counter-protesters – some of whom said they were from Beverly Hills – peaked at around 30 people.",
    byline: '(Zoraiz Irshad/Daily Bruin senior staff)',
    date: '4/27',
    fulldate: 'April 27, 2024 11:01 p.m.',
    },
    {
    name: 'photo41',
    title: "Harassment of encampment",
    image: 'DSC_4937',
    description: "During the third night of the demonstration, counter-protesters continued to harass encampment participants, shout into megaphones and play loud music to prevent pro-Palestine protesters from sleeping. Meanwhile, encampment participants were peaceful and quiet as they continued their nightly routines.",
    byline: '(Zoraiz Irshad/Daily Bruin senior staff)',
    date: '4/27',
    fulldate: 'April 27, 2024 11:12 p.m.',
    },
    {
    name: 'photo42',
    title: "Encampment art station",
    image: 'DSC_4738',
    description: "Over the course of the encampment, protesters expressed their solidarity with Palestine and frustration with the UC through art. Organizers raised thousands of dollars through donations to help cover costs for food and supplies.",
    byline: '(Zoraiz Irshad/Daily Bruin senior staff)',
    date: '4/27',
    fulldate: 'April 27, 2024 7:18 p.m.',
    },
    {
    name: 'photo43',
    title: "Rented pickup trucks",
    image: 'DSC_4820',
    description: "Some members of the encampment rented pickup trucks to bring wooden pallets to fortify barriers. Demonstrators added protection throughout the week the encampment was present.",
    byline: '(Zoraiz Irshad/Daily Bruin senior staff)',
    date: '4/27',
    fulldate: 'April 27, 2024 10:34 p.m.',
    },
    {
    name: 'photo44',
    title: "Ambulances arrive",
    image: 'DBJ_9294',
    description: "Following several 911 calls made by pro-Palestine protesters after multiple counter-protesters attempted to climb over barricades and push past demonstrators, ambulances and paramedics arrived on the scene.",
    byline: '(Joseph Crosby/Daily Bruin senior staff)',
    date: '4/28',
    fulldate: 'April 28, 2024 12:06 a.m.',
    },
    {
    name: 'photo45',
    title: "Security easing tensions",
    image: 'DSC_5558',
    description: "CSC security officers hired by UCLA attempted to ease tensions as multiple counter-protesters tried to forcibly enter the encampment in the early morning April 28.",
    byline: '(Zoraiz Irshad/Daily Bruin senior staff)',
    date: '4/28',
    fulldate: 'April 28, 2024 12:07 a.m.',
    },
    {
    name: 'photo46',
    title: "Extending barriers",
    image: 'DBJ_9593',
    description: "Encampment participants extended barriers up to the entrances of Powell Library and Royce Hall. The expanded area of the encampment stretched from the top of Janss Steps to the east end of Royce Hall. ",
    byline: '(Joseph Crosby/Daily Bruin senior staff)',
    date: '4/28',
    fulldate: 'April 28, 2024 1:33 a.m.',
    },
    {
    name: 'photo47',
    title: "Pro-Israel rally speeches",
    image: 'DBJ_1025',
    description: "A woman speaks at the pro-Israel rally. The rally kicked off around 11 a.m. with musical performances and was followed by numerous speeches.",
    byline: '(Anna Dai-Liu/Daily Bruin senior staff)',
    date: '4/28',
    fulldate: 'April 28, 2024 10:47 p.m.',
    },
    {
    name: 'photo48',
    title: "Linking arms on Janss Steps",
    image: '0DB_9149',
    description: "Pro-Palestine protesters linked arms near the top of Janss Steps, blocking access to the encampment. A group of counter-protesters had gathered at the foot of the steps around the same time.",
    byline: '(Nicolas Greamo/Daily Bruin senior staff)',
    date: '4/28',
    fulldate: 'April 28, 2024 12:10 p.m.',
    },
    {
    name: 'photo49',
    title: "UCPD dispersement after pro-Israel rally",
    image: 'DSC_0188',
    description: "As pro-Israel counter-protesters began to disperse at the end of the rally, they faced off with pro-Palestine protesters. UCPD officers in riot gear responded by lining up near the flagpole in Dickson Plaza, while pro-Palestine protesters assembled on Portola Plaza.",
    byline: '(Brandon Morquecho/Daily Bruin senior staff)',
    date: '4/28',
    fulldate: 'April 28, 2024 1:28 p.m.',
    },
    {
    name: 'photo50',
    title: "Protesters exchanging words",
    image: 'DSC_0365',
    description: "Lines of pro-Palestine and pro-Israel protesters stood feet apart, exchanging words and hurling insults.",
    byline: '(Brandon Morquecho/Daily Bruin senior staff)',
    date: '4/28',
    fulldate: 'April 28, 2024 1:33 p.m.',
    },
    {
    name: 'photo51',
    title: "UCPD and CSC separating protesters at pro-Israel rally",
    image: 'DSC_0522',
    description: "As UCPD and CSC security staff formed lines close to protesters in Portola Plaza, pro-Israel counter-protesters had mostly dispersed, while pro-Palestine protesters had migrated near the Inverted Fountain.",
    byline: '(Brandon Morquecho/Daily Bruin senior staff)',
    date: '4/28',
    fulldate: 'April 28, 2024 1:40 p.m.',
    },
    {
    name: 'photo52',
    title: "Pro-Palestine protesters walk across campus",
    image: 'DSC_0695',
    description: "After the rally, a large group of pro-Palestine protesters walked through campus before stopping between Pauley Pavilion and the Central Ticket Office. ",
    byline: '(Brandon Morquecho/Daily Bruin senior staff)',
    date: '4/28',
    fulldate: 'April 28, 2024 1:52 p.m.',
    },
    {
    name: 'photo53',
    title: "Heated argument between protesters and security",
    image: 'DSC_9134',
    description: "A man with blood dripping from his temple approached a CSC security staff member, shouting while pointing toward Powell Library. A few moments later, a group of pro-Israel counter-protesters approached to engage in the argument.",
    byline: '(Brandon Morquecho/Daily Bruin senior staff)',
    date: '4/28',
    fulldate: 'April 28, 2024 10:46 a.m.',
    },
    {
    name: 'photo54',
    title: "Pro-Israel rally speakers",
    image: 'DSC_9229',
    description: "After raising over $67,000 by the morning of April 28, the Israeli American Council held a pro-Israel rally in Dickson Plaza, less than 100 yards from the encampment. IAC organizers invited speakers including Jonathan Greenblatt, CEO of the Anti-Defamation League, and Dan Gold, executive director of Hillel at UCLA.",
    byline: '(Brandon Morquecho/Daily Bruin senior staff)',
    date: '4/28',
    fulldate: 'April 28, 2024 10:59 a.m.',
    },
    {
    name: 'photo55',
    title: "Altercations at pro-Israel rally",
    image: 'DSC_9445',
    description: "Portions of the competing protests became tense as pro-Israel and pro-Palestine demonstrators confronted each other.",
    byline: '(Brandon Morquecho/Daily Bruin senior staff)',
    date: '4/28',
    fulldate: 'April 28, 2024 11:17 a.m.',
    },
    {
    name: 'photo56',
    title: "Pro-Israel rally audience",
    image: 'DSC_9847',
    description: "The pro-Israel rally organized by the Israeli American Council attracted over a thousand counter-protesters. At 10:30 a.m., a group of demonstrators in support of the encampment pushed down the barriers surrounding the rally, which had been put up by UCPD and facilities staff, but later vacated the area.",
    byline: '(Brandon Morquecho/Daily Bruin senior staff)',
    date: '4/28',
    fulldate: 'April 28, 2024 11:36 a.m.',
    },
    {
    name: 'photo57',
    title: "Quiet from the encampment",
    image: 'DBJ_0703',
    description: "While the pro-Israel protesters assembled in Dickson Plaza, onlookers from inside the encampment remained peaceful for the entirety of the rally.",
    byline: '(Nicolas Greamo/Daily Bruin senior staff)',
    date: '4/28',
    fulldate: 'April 28, 2024 9:50 a.m.',
    },
    {
    name: 'photo58',
    title: "Chants in Bruin Plaza",
    image: 'IMG_9921',
    description: "Organizers in Bruin Plaza gave speeches and led chants such as, “What do we want? Justice. When do we want it? Now!”",
    byline: '(Zimo Li/Photo Editor)',
    date: '4/29',
    fulldate: 'April 29, 2024 12:45 p.m.',
    },
    {
    name: 'photo59',
    title: "Start of campus tour",
    image: 'DSC03165',
    description: "Students, faculty and community members assembled near Bunche Hall before beginning their tour of campus shortly after noon.",
    byline: '(Anna Dai-Liu/Daily Bruin senior staff)',
    date: '4/29',
    fulldate: 'April 29, 2024 11:03 a.m.',
    },
    {
    name: 'photo60',
    title: "Expanding borders",
    image: 'DSC_6439',
    description: "After encampment participants expanded the area within their barriers in the early morning of April 28, the size of the encampment grew as more tents were set up.",
    byline: '(Karla Cardenas-Felipe/Daily Bruin)',
    date: '4/29',
    fulldate: 'April 29, 2024 12:37 p.m.',
    },
    {
    name: 'photo61',
    title: "Palestine solidarity rally",
    image: 'DSC_6449',
    description: "Protesters gathered inside the encampment for a solidarity rally led by Faculty for Justice in Palestine and Students for Justice in Palestine at UCLA, where students and faculty members gave speeches calling on the UC to abide by the protesters' demands. ",
    byline: '(Karla Cardenas-Felipe/Daily Bruin)',
    date: '4/29',
    fulldate: 'April 29, 2024 12:46 p.m.',
    },
    {
    name: 'photo62',
    title: "Day 5 of encampment",
    image: 'DSC_6503',
    description: "On the fifth day of the encampment, thousands of faculty, students and community members came together to support the encampment. The protesters traveled through much of campus, starting near Bunche Hall before making their way to Bruin Plaza.",
    byline: '(Karla Cardenas-Felipe/Daily Bruin)',
    date: '4/29',
    fulldate: 'April 29, 2024 1:24 p.m.',
    },
    {
    name: 'photo63',
    title: "Large crowd in Bruin Plaza",
    image: 'DSC_6522',
    description: "In Bruin Plaza, over 1,000 participants gathered around the stage to join chants led by members of Students for Justice in Palestine and the UC Divest Coalition at UCLA.",
    byline: '(Karla Cardenas-Felipe/Daily Bruin)',
    date: '4/29',
    fulldate: 'April 29, 2024 1:34 p.m.',
    },
    {
    name: 'photo64',
    title: "Making way through Royce Hall",
    image: 'DBJ_1847',
    description: "Hundreds of students forced their way through Royce Hall's rear entrance before lining up under the archways in front of the building to hear speeches from inside the encampment.",
    byline: '(Leydi Cris Cobo Cordon/Daily Bruin senior staff)',
    date: '4/29',
    fulldate: 'April 29, 2024 11:56 a.m.',
    },
    {
    name: 'photo65',
    title: "Cheers for faculty in solidarity",
    image: 'DSC_3689',
    description: "Faculty members made their way from Bunche Hall to the pathway between Kaplan Hall and Powell Library. Demonstrators inside the encampment cheered and applauded as faculty members were let inside.",
    byline: '(Mia Tavares/Daily Bruin senior staff)',
    date: '4/29',
    fulldate: 'April 29, 2024 1:08 p.m.',
    },
    {
    name: 'photo66',
    title: "Midnight fights",
    image: 'DBJ_2515',
    description: "Around 11 p.m., 30 counter-protesters arrived at Dickson Plaza and began harassing protesters inside the encampment. Less than an hour later, counter-protesters attempted to forcefully enter the entrance to the encampment between Powell Library and Kaplan Hall. Around midnight, UCPD officers wearing riot gear arrived at the scene, causing the 60 or so counter-protesters to vacate the area.",
    byline: '(Dylan Winward/Daily Bruin senior staff)',
    date: '4/29',
    fulldate: 'April 29, 2024 10:37 p.m.',
    },
    {
    name: 'photo67',
    title: "Counter-protesters wear white masks",
    image: 'DSC_6670',
    description: "On the evening of the encampment's sixth day, around 100 counter-protesters assembled in Dickson Plaza, with some wearing masks to protect their identity. ",
    byline: '(Zoraiz Irshad/Daily Bruin senior staff)',
    date: '4/30',
    fulldate: 'April 30, 2024 10:44 p.m.',
    },
    {
    name: 'photo68',
    title: "Upgraded barriers",
    image: 'DSC_6771',
    description: "Encampment participants made significant upgrades to the surrounding barriers ahead of the attack on the encampment. As counter-protesters violently attacked the encampment, members inside attempted to hold the barriers intact.",
    byline: '(Zoraiz Irshad/Daily Bruin senior staff)',
    date: '4/30',
    fulldate: 'April 30, 2024 10:49 p.m.',
    },
    {
    name: 'photo69',
    title: "Counter-protester spraying aerosol",
    image: 'DSC_6838',
    description: "A counter-protester dressed in black sprayed an aerosol onto people inside the encampment. Throughout the night, counter-protesters sprayed noxious gasses at members of the encampent.",
    byline: '(Zoraiz Irshad/Daily Bruin senior staff)',
    date: '4/30',
    fulldate: 'April 30, 2024 10:53 p.m.',
    },
    {
    name: 'photo70',
    title: "Violent attacks by counter-protesters",
    image: 'DSC_6989',
    description: "During the night and early morning after parts of the barricade were torn down, counter-protesters attacked pro-Palestine protesters and threw objects at the encampment. By the end of the night, 25 protesters from the encampment were hospitalized, a spokesperson from UC Divest Coalition at UCLA said during a press conference the next day.",
    byline: '(Zoraiz Irshad/Daily Bruin senior staff)',
    date: '4/30',
    fulldate: 'April 30, 2024 11:04 p.m.',
    },
    {
    name: 'photo71',
    title: "911 calls",
    image: 'DSC_7162',
    description: "The acts of violence led to numerous calls to 911, prompting the arrival of emergency medical services. ",
    byline: '(Zoraiz Irshad/Daily Bruin senior staff)',
    date: '4/30',
    fulldate: 'April 30, 2024 11:13 p.m.',
    },
    {
    name: 'photo72',
    title: "Fireworks",
    image: 'DSC_7313',
    description: "Around 11 p.m., counter-protesters shot fireworks at the encampment. Throughout the night, counter-protesters released several fireworks.",
    byline: '(Zoraiz Irshad/Daily Bruin senior staff)',
    date: '4/30',
    fulldate: 'April 30, 2024 11:37 p.m.',
    },
    {
    name: 'photo73',
    title: "Firework exploding on barricade",
    image: 'DBJ_3654',
    description: "A firework explodes at the base of the encampment barrier, creating a bright flash of light followed by a plume of smoke.",
    byline: '(Daily Bruin file photo)',
    date: '4/30',
    fulldate: 'April 30, 2024 10:01 p.m.',
    },
    {
    name: 'photo74',
    title: "Officers arrive",
    image: 'DSC_3173',
    description: "Around 1:50 a.m. a group of law enforcement officers assembled at the edge of Dickson Plaza near the flagpole. For an hour, officers stood watching the violence occur before slowly proceeding toward the encampment barricade.",
    byline: '(Zoraiz Irshad/Daily Bruin senior staff)',
    date: '5/1',
    fulldate: 'May 1, 2024 1:47 a.m.',
    },
    {
    name: 'photo75',
    title: "Gas masks",
    image: 'DSC_3709',
    description: "California Highway Patrol officers, many wearing gas masks, stand at the pathway between Powell Library and Kaplan Hall.",
    byline: '(Zoraiz Irshad/Daily Bruin senior staff)',
    date: '5/1',
    fulldate: 'May 1, 2024 1:54 a.m.',
    },
    {
    name: 'photo76',
    title: "California Highway Patrol lines up by flagpole",
    image: 'DSC_5658',
    description: "CHP officers armed with batons and other less-than-lethal weapons stand by the flagpole in Dickson Plaza as protesters watch on from the side. During the sweep, law enforcement officers repeatedly used flash-bang devices, producing large booms throughout the night and early morning until at least 6:25 a.m.",
    byline: '(Jeremy Chen/Daily Bruin senior staff)',
    date: '5/1',
    fulldate: 'May 1, 2024 1:50 a.m.',
    },
    {
    name: 'photo77',
    title: "Clouds of gas at barriers",
    image: 'JSC_4078',
    description: "A large cloud of gas covers one side of the encampment barrier. Over the several hours of attacks, the encampment was bombarded with tear gas, pepper spray and various noxious gasses.",
    byline: '(Jeremy Chen/Daily Bruin senior staff)',
    date: '5/1',
    fulldate: 'May 1, 2024 12:21 a.m.',
    },
    {
    name: 'photo78',
    title: "Eye irritants used on encampment",
    image: 'JSC_4333',
    description: "A pro-Palestine protester has an irritant washed out of their eyes. Throughout the night, many protesters were treated for eye irritation caused by pepper spray, tear gas or other irritants.",
    byline: '(Jeremy Chen/Daily Bruin senior staff)',
    date: '5/1',
    fulldate: 'May 1, 2024 1:05 a.m.',
    },
    {
    name: 'photo79',
    title: "Encampment participants protect barriers",
    image: 'JSC_4248',
    description: "While counter-protesters continued to tear down the barriers, protesters inside the encampment attempted to stop the attackers' advances. Protesters tried to hold onto barricades as aggressors pulled them away.",
    byline: '(Jeremy Chen/Daily Bruin senior staff)',
    date: '5/1',
    fulldate: 'May 1, 2024 12:43 a.m.',
    },
    {
    name: 'photo80',
    title: "Staredown at barricade",
    image: 'JSC_4360',
    description: "Counter-protesters stand a few yards away from the encampment barriers as a liquid is sprayed from inside the encampment. One of the counter-protesters holds a flag with \"Moshiach\" – the Hebrew word for \"the anointed one\" – on it, referring to the Messiah in Judaism.",
    byline: '(Jeremy Chen/Daily Bruin senior staff)',
    date: '5/1',
    fulldate: 'May 1, 2024 1:17 a.m.',
    },
    {
    name: 'photo81',
    title: "Law enforcement prepares for clearing out",
    image: 'JSC_4940',
    description: "Law enforcement officers line up in Dickson Plaza just before 3 a.m. before clearing out the remaining counter-protesters.",
    byline: '(Jeremy Chen/Daily Bruin senior staff)',
    date: '5/1',
    fulldate: 'May 1, 2024 2:57 a.m.',
    },
    {
    name: 'photo82',
    title: "Pro-Palestine protester kneels in front of CHP",
    image: 'JSC_4982',
    description: "A pro-Palestine protester kneels in front of two California Highway Patrol officers with their head in their hands.",
    byline: '(Jeremy Chen/Daily Bruin senior staff)',
    date: '5/1',
    fulldate: 'May 1, 2024 3:06 a.m.',
    },
    {
    name: 'photo83',
    title: "Encampment braces for sweep",
    image: 'DSC_4323',
    description: "Pro-Palestine protesters linked arms on Janss Steps as thousands came to show support for the encampment and brace for the ensuing police sweep. Around 3 p.m., encampment organizers held a press conference at the bottom of Janss Steps.",
    byline: '(Brandon Morquecho/Daily Bruin senior staff)',
    date: '5/1',
    fulldate: 'May 1, 2024 4:44 p.m.',
    },
    {
    name: 'photo84',
    title: "Law enforcement in Haines Hall",
    image: 'DSC_5789',
    description: "Law enforcement officers fiIed into Haines Hall around 9:30 p.m. as protesters in support of the encampment shouted, \"Shame.\"",
    byline: '(Brandon Morquecho/Daily Bruin senior staff)',
    date: '5/1',
    fulldate: 'May 1, 2024 9:30 p.m.',
    },
    {
    name: 'photo85',
    title: "Rebuilding barriers",
    image: 'DSC_6157',
    description: "Recovering from the counter-protesters' violent attacks on the encampment, members of the encampment spent time rebuilding the barriers torn down the night before.",
    byline: '(Brandon Morquecho/Daily Bruin senior staff)',
    date: '5/1',
    fulldate: 'May 1, 2024 11:34 a.m.',
    },
    {
    name: 'photo86',
    title: "Law enforcement gathers in Wilson Plaza",
    image: 'https://wp.dailybruin.com/images/2024/05/web.news_.breaking.priortosweep.b.zl_.jpg',
    description: "Law enforcement vehicles gathered in Wilson Plaza ahead of the following sweep. Several different departments began amassing Wednesday afternoon, including officers from the California Highway Patrol, Los Angeles County Sheriff's Department, UCPD, LAPD and the Santa Monica Police Department. The cars began leaving Wilson Plaza shortly before 8 p.m.",
    byline: '(Zimo Li/Photo Editor)',
    date: '5/1',
    fulldate: 'May 1, 2024 4:43 p.m.',
    },
    {
    name: 'photo87',
    title: "Volunteer medics",
    image: 'DSC03480',
    description: "Volunteer medics set up an aid station in preparation for the following morning's sweep. These medics, which included pre-med students and UCLA physicians alike, helped provide immediate medical care to those injured during the violence of April 30 and May 2.",
    byline: '(Anna Dai-Liu/Daily Bruin senior staff)',
    date: '5/1',
    fulldate: 'May 1, 2024 5:45 p.m.',
    },
    {
    name: 'photo88',
    title: "Police group in Dickson Plaza",
    image: 'JSC_5195',
    description: "Police officers formed a line in Dickson Plaza facing the encampment. Earlier that day, law enforcement had placed barriers along the eastern entrance to the plaza by the flagpole. ",
    byline: '(Jeremy Chen/Daily Bruin senior staff)',
    date: '5/1',
    fulldate: 'May 1, 2024 6:19 p.m.',
    },
    {
    name: 'photo89',
    title: "Protesters atop scaffolding",
    image: 'DSC_7581',
    description: "Several members of the encampment stood atop scaffolding by Powell Library on May 1. The day before, UCPD detained a protester who climbed the scaffolding before releasing them a little over an hour later. ",
    byline: '(Zoraiz Irshad/Daily Bruin senior staff)',
    date: '5/1',
    fulldate: 'May 1, 2024 6:41 p.m.',
    },
    {
    name: 'photo90',
    title: "LAPD officers at Janss Steps",
    image: 'DSC_6386',
    description: "Four LAPD officers in riot gear stood at the top of Janss Steps while pro-Palestine protesters filmed them.",
    byline: '(Brandon Morquecho/Daily Bruin senior staff)',
    date: '5/2',
    fulldate: 'May 2, 2024 12:56 a.m.',
    },
    {
    name: 'photo91',
    title: "LAPD officer drags pro-Palestine protester",
    image: 'DSC_6394',
    description: "An LAPD officer dragged a pro-Palestine protester by the back of their hoodie as law enforcement engaged with members of the encampment.",
    byline: '(Brandon Morquecho/Daily Bruin senior staff)',
    date: '5/2',
    fulldate: 'May 2, 2024 12:22 a.m.',
    },
    {
    name: 'photo92',
    title: "Officers await instructions",
    image: 'DSC_6721',
    description: "Several law enforcement officers stood in front of the encampment's barrier while both law enforcement and protesters waited for the sweep to begin. ",
    byline: '(Brandon Morquecho/Daily Bruin senior staff)',
    date: '5/2',
    fulldate: 'May 2, 2024 12:37 a.m.',
    },
    {
    name: 'photo93',
    title: "Riot gear and zip tie handcuffs",
    image: 'JSC_5407',
    description: "Officers wearing riot gear grouped by the southwestern corner of Haines Hall, equipped with zip tie handcuffs and batons at the ready. ",
    byline: '(Jeremy Chen/Daily Bruin senior staff)',
    date: '5/2',
    fulldate: 'May 2, 2024 3:04 a.m.',
    },
    {
    name: 'photo94',
    title: "Officers by Student Activities Center",
    image: 'DSC_4757',
    description: "A group of law enforcement officers stood on a path between the Student Activities Center and the lawn south of Janss Steps. The officers proceeded to regroup in Wilson Plaza before being called away.",
    byline: '(Joseph Crosby/Daily Bruin senior staff)',
    date: '5/2',
    fulldate: 'May 2, 2024 12:53 a.m.',
    },
    {
    name: 'photo95',
    title: "Protesters remain on Janss Steps",
    image: 'DSC_5224',
    description: "Hundreds of protesters remained on Janss Steps through the early hours of May 2. Many protesters wore goggles and helmets in anticipation of violence from the police.",
    byline: '(Joseph Crosby/Daily Bruin senior staff)',
    date: '5/2',
    fulldate: 'May 2, 2024 1:02 a.m.',
    },
    {
    name: 'photo96',
    title: "Protester overturns trash cans",
    image: 'DSC_8419',
    description: "A protester turned trash cans on their sides, creating more obstacles for law enforcement to traverse before entering the encampment.",
    byline: '(Zoraiz Irshad/Daily Bruin senior staff)',
    date: '5/2',
    fulldate: 'May 2, 2024 3:05 a.m.',
    },
    {
    name: 'photo97',
    title: "Sheriff buses assemble",
    image: 'DSC_6778',
    description: "Los Angeles County Sheriff's Department buses assembled on Royce Drive. By the end of the night, over 200 protesters had been detained. The first detainment, as reported by the Daily Bruin, took place around 2 a.m.",
    byline: '(Myka Fromm/Daily Bruin senior staff)',
    date: '5/2',
    fulldate: 'May 2, 2024 2:02 a.m.',
    },
    {
    name: 'photo98',
    title: "Stand-off at the Inverted Fountain",
    image: 'aftermathgallery',
    description: "Police wearing riot gear and carrying less-than-lethal weapons faced a crowd of protesters early Thursday morning near the Inverted Fountain. As protesters chanted together, the police slowly advanced their lines. Ultimately, however, a physical confrontation was avoided and both groups departed in opposite directions.",
    byline: '(Nicolas Greamo/Daily Bruin senior staff)',
    date: '5/2',
    fulldate: 'May 2, 2024 5:39 a.m.',
    },
    {
    name: 'photo99',
    title: "Last encampment holdouts",
    image: 'DSC_8021',
    description: "At 6 a.m., a small group of protesters remained at the top of Janss Steps, chanting in unison.",
    byline: '(Nicolas Greamo/Daily Bruin senior staff)',
    date: '5/2',
    fulldate: 'May 2, 2024 6:10 a.m.',
    },
    {
    name: 'photo100',
    title: "Chants in late morning",
    image: 'DSC_8294',
    description: "The remaining protesters stood face-to-face with California Highway Patrol officers. After over an hour of chanting, the last of the protesters left the area.",
    byline: '(Nicolas Greamo/Daily Bruin senior staff)',
    date: '5/2',
    fulldate: 'May 2, 2024 6:19 a.m.',
    },
    {
    name: 'photo101',
    title: "Encampment in ruin",
    image: 'DSC_8876',
    description: "Remnants of the encampment barricade were left strewn about the ground of Dickson Plaza. Almost nothing from the encampment remained intact.",
    byline: '(Nicolas Greamo/Daily Bruin senior staff)',
    date: '5/2',
    fulldate: 'May 2, 2024 6:44 a.m.',
    },
  // {
  //   name: 'photo',
  //   title: '',
  //   image: '',
  //   description: "",
  //   byline: "",
  //   date: "",
  //   fulldate: "May 1, 2024"
  // },

]

function Popup(props) {
  return (props.trigger) ? (
    <div className="popup">
      <div className="popup-inner">
        <div className="fulldate">
          {content[props.popupTitle].fulldate}
        </div>
        <h2>{content[props.popupTitle].title}</h2>
        <br />
        <img src={content[props.popupTitle].image} alt='altText' width="100%" height="100%" />
        <br />
        <p style={{ marginTop: "10px" }}> {content[props.popupTitle].description} </p>
        <div className='byline'>
          {content[props.popupTitle].byline}
        </div>
        <div className='close-btn' onClick={() => props.setTrigger(false)}>
          <svg xmlns="http://www.w3.org/2000/svg"
            height="24px"
            viewBox="0 -960 960 960"
            width="24px"
            fill="#000000"
            alt='Close'>
            <path d="m256-200-56-56 224-224-224-224 56-56 224 224 224-224 56 56-224 224 224 224-56 56-224-224-224 224Z" /></svg>
        </div>
        {props.children}
      </div>
    </div>
  ) : "";
}

export default Popup